name: Deploy site via Fleek
on: push
jobs:
  deploy-to-fleek:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: pat_I9XVDV7flKDCy3QTb2nk
      FLEEK_PROJECT_ID: cllfjg9650011lc089cxajsy7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Fleek CLI
        run: npm i -g @fleekxyz/cli
      - name: Install Packages
        run: yarn install
      - name: Build & deploy sites
        run: fleek sites deploy
